// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package input

import (
	"github.com/sony-nurdianto/test_driven_development/chapter03/calculator"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationProcessor creates a new instance of MockOperationProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationProcessor {
	mock := &MockOperationProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationProcessor is an autogenerated mock type for the OperationProcessor type
type MockOperationProcessor struct {
	mock.Mock
}

type MockOperationProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationProcessor) EXPECT() *MockOperationProcessor_Expecter {
	return &MockOperationProcessor_Expecter{mock: &_m.Mock}
}

// ProcessOperation provides a mock function for the type MockOperationProcessor
func (_mock *MockOperationProcessor) ProcessOperation(operation calculator.Operation) (*string, error) {
	ret := _mock.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for ProcessOperation")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(calculator.Operation) (*string, error)); ok {
		return returnFunc(operation)
	}
	if returnFunc, ok := ret.Get(0).(func(calculator.Operation) *string); ok {
		r0 = returnFunc(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(calculator.Operation) error); ok {
		r1 = returnFunc(operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationProcessor_ProcessOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessOperation'
type MockOperationProcessor_ProcessOperation_Call struct {
	*mock.Call
}

// ProcessOperation is a helper method to define mock.On call
//   - operation calculator.Operation
func (_e *MockOperationProcessor_Expecter) ProcessOperation(operation interface{}) *MockOperationProcessor_ProcessOperation_Call {
	return &MockOperationProcessor_ProcessOperation_Call{Call: _e.mock.On("ProcessOperation", operation)}
}

func (_c *MockOperationProcessor_ProcessOperation_Call) Run(run func(operation calculator.Operation)) *MockOperationProcessor_ProcessOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 calculator.Operation
		if args[0] != nil {
			arg0 = args[0].(calculator.Operation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationProcessor_ProcessOperation_Call) Return(s *string, err error) *MockOperationProcessor_ProcessOperation_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOperationProcessor_ProcessOperation_Call) RunAndReturn(run func(operation calculator.Operation) (*string, error)) *MockOperationProcessor_ProcessOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidationHelper creates a new instance of MockValidationHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidationHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidationHelper {
	mock := &MockValidationHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidationHelper is an autogenerated mock type for the ValidationHelper type
type MockValidationHelper struct {
	mock.Mock
}

type MockValidationHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidationHelper) EXPECT() *MockValidationHelper_Expecter {
	return &MockValidationHelper_Expecter{mock: &_m.Mock}
}

// CheckInput provides a mock function for the type MockValidationHelper
func (_mock *MockValidationHelper) CheckInput(operator string, operands []float64) error {
	ret := _mock.Called(operator, operands)

	if len(ret) == 0 {
		panic("no return value specified for CheckInput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []float64) error); ok {
		r0 = returnFunc(operator, operands)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidationHelper_CheckInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInput'
type MockValidationHelper_CheckInput_Call struct {
	*mock.Call
}

// CheckInput is a helper method to define mock.On call
//   - operator string
//   - operands []float64
func (_e *MockValidationHelper_Expecter) CheckInput(operator interface{}, operands interface{}) *MockValidationHelper_CheckInput_Call {
	return &MockValidationHelper_CheckInput_Call{Call: _e.mock.On("CheckInput", operator, operands)}
}

func (_c *MockValidationHelper_CheckInput_Call) Run(run func(operator string, operands []float64)) *MockValidationHelper_CheckInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []float64
		if args[1] != nil {
			arg1 = args[1].([]float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValidationHelper_CheckInput_Call) Return(err error) *MockValidationHelper_CheckInput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidationHelper_CheckInput_Call) RunAndReturn(run func(operator string, operands []float64) error) *MockValidationHelper_CheckInput_Call {
	_c.Call.Return(run)
	return _c
}
